from os import environ

use_endpoint_address = "http://127.0.0.1:5001"
if environ.get("OR_IP") is not None:
    use_endpoint_address = environ.get("OR_IP")


DEFAULT_TYPE_IDS = ['ROR_Org',
    'OpenAlex_Org',
    'ISNI_Person',
    'GND_Person',
    'BnF_Person',
    'BNE_Person',
    'NDL_Person',
    'OpenCorporates_Org',
    'LCNAF_Person',
    'NTA_Person',
    'OpenLibrary_Author',
    'AAT_Award',
    'DataCite_Award',
    'GeoNames_Location',
    'TGN_Location',
    'Academy_Award',
    'NSF_Award',
    'PEN_Org',
    'Members_Org',
    'ACLS_Org',
    'IFLA_Org',
    'ISC_Org',
    'Alberta_Place',
    'OpenLibrary_Work',
    'SF_Awards_Person',
    'ACM_Awards_Person',
    'RSC_Fellow',
    'TWAS_Fellow',
    'EBU_Org',
    'EUNIC_Org',
    'ADB_Person',
    'ACM_Person',
    'BNMX_Person',
    'AIATSIS_Place',
    'Canada_Historic_Place',
    'ASCE_Landmark_Place',
    'ADB_Publication_Work',
    'AAGM_Artwork_Work',
    'Euro08_Winner',
    'TwoGIS_Place',
    'Academy_Awards_Film',
    'AwardsWinners_Artist',
    'ASCAP_Work',
    'HAL_Org',
    'AwardsWinners_Person',
    'ALS_Org',
    'AAA_Org',
    'JTI_Org',
    'AEDA_Place',
    'MedalHonor_Person',
    'AINM_Place',
    'ACER_Org',
    'ACUM_Org',
    'Euro08_Person',
    'HebrewTheatre_Person',
    'AMPAS_Item',
    'ANPI_Place',
    'SevenDays_Person',
    'AAA_UK_Org',
    'ADAL_Spain_Org',
    'Bavarian_Monument_Place',
    'Australian_Heritage_Place_2',
    'AILA_Org',
    'Altexto_Org',
    'Sloan_Prize',
    'AMPAS_Person_2',
    'AJOL_Org',
    'AJUP_Org',
    'AtomicHeritage_Org',
    'Antarctic_Place',
    'BaneNOR_Place',
    'ALCA_Person',
    'ALCUIN_Person',
    'AMNH_Org',
    'NYC_Art_Place',
    'ACNC_Org',
    'Georgia_Emigrants_Person',
    'CESAR_Person',
    'ARC_Grant',
    'OpenDOAR_Org',
    'RS_Memoirs_Person',
    'Rome_Fellow_Person',
    'Royal_Society_Person',
    'SAM_Gov_Org',
    'HAL_TEL_Work',
    'ACM_Author_Id',
    'JapanNTA_Org',
    'SherpaRomeo_Work',
    'IPEDS_Org',
    'Nobel_Person',
    'SECCIK_Org',
    'JTI_Org_2',
    'EU_Transparency_Org',
    'ERIHPLUS_Journal',
    'Crossref_Funder_Org',
    'ABEU_Org',
    'AfricanMinds_Org',
    'AlbinMichel_Person',
    'GrantNav_Prize',
    'AFNIL_Org',
    'ASEUC_Org',
    'AlternativaTeatral_Place',
    'BHF_Person',
    'REUN_Org',
    'AAGM_Org',
    'ReliefWeb_Org',
    'AmericanHeritage_Place',
    'ISIL_Org',
    'ODUCAL_Org',
    'AFAS_Person',
    'Ads_Work',
    'Antarctic_Place_2',
    'IFACCA_Org',
    'AGORHA_Person',
    'ACE_Org',
    'Bombardirov_Person',
    'ADB_Org_Auth',
    'AEF_Org',
    'ALPSP_Org',
    'ASALE_Org',
    're3data_Org',
    'RussianDict_Person',
    'ChineseBio_Person',
    'QueerScientists_Person',
    'AAMC_Org',
    'AALA_Org',
    'BabelNet_Entity',
    'CODEN_Work',
    'EuropePMC_Work',
    'OpenCitations_Work',
    'ThreeSixtyGiving_Org',
    'Grammy_Award',
    'Sirene_Org',
    'DOAJ_Journal',
    'IdRef_Person',
    'SBN_Work',
    'BVMC_Person',
    'GCD_Publisher',
    'SIC_Mexico',
    'GRID_Historical',
    'ProPublica_Org',
    'NLA_Person',
    'ANZL_Writer',
    'Academy_Awards_Nominee',
    'Akadem_Person',
    'Annuaire_Fondations_Org',
    'LC_Work_Id',
    'Google_Books',
    'OCLC_Record',
    'HathiTrust',
    'VIAF_Title',
    'Wikidata_Title',
    'OpenLibrary_Title',
    'ACA_Person',
    'RS_Past_Fellow_Person',
    'Ads_Winner',
    'FIPB_Org',
    'AUP_NZ_Org',
    'Israel_Art_Person',
    'Israel_Antiquities_Place',
    'Israel_Museum_Person',
    'Israel_Company_Org',
    'Mexico_Aviation_Org',
    'Mexico_Museums_Place',
    'SA_English_Work',
    'EULAC_Org',
    'NLI_Israel_Org',
    'Egyptian_Museum_Org',
    'MinCiencias_Colombia_Org',
    'Nigeria_NL_Org',
    'Nigerian_Company_Org',
    'SNIESS_Colombia_Org',
    'Vietnam_Company_Org',
    'AGN_Colombia_Org',
    'CanTho_Vietnam_Org',
    'Egypt_GAFI_Org',
    'BaFin_Org',
    'Premiados_Person',
    'Slovakia_History_Work',
    'Psychiatry_Bio_Person',
    'Czech_Bio_Person',
    'Bulgarian_Antarctic_Place',
    'PBN_Org',
    'AEUP_Org',
    'Algerian_NL_Person',
    'Bavarian_Monument_Auth_Place',
    'BALaT_Person',
    'ArtHistorians_Person',
    'Indy_Place',
    'GRC_Org',
    'AICTE_Org',
    'AISHE_Org',
    'AJOL_Org_2',
    'ASCL_Work',
    'Leiden_Place',
    'ASI_Place',
    'CiNii_Org',
    'Garuda_Org_2',
    'Indo_College_Org',
    'BNB_Person',
    'Akadem_Person_2',
    'Brapci_Person',
    'CNKI_Person',
    'OASPA_Org',
    'ACUP_Org',
    'UNE_Org',
    'AArU_Org',
    'UPI_Org',
    'CEEOL_Org',
    'CLACSO_Org',
    'ASSAf_Org',
    'Garuda_Org',
    'MyJurnal_Org',
    'ABU_Org',
    'AFPU_Org',
    'AG_Univerlage_Org',
    'KUPA_Org',
    'CUPA_Org',
    'DOAB_Org',
    'CharityCommission_Org',
    'ProjectMUSE_Org',
    'JSTOR_Org',
    'Indonesia_Place',
    'CWGC_Person',
    'CGIAR_Org',
    'IPA_Org',
    'PASA_Org',
    'UPAN_Org',
    'AaRC_Winner',
    'RussianTV_Winner',
    'IRINS_Org',
    'Barcelona_Heritage_Place',
    'Gatehouse_Place',
    'ARTIC_Person',
    'ARTIC_Work',
    'ASEE_Person',
    'Drammen_Place',
    'ELEM_Org',
    'Athens_Academy_Person',
    'Rome_Academy_Person',
    'French_Academy_Science_Person',
    'Korean_Academy_Science_Person',
    'Liszt_Academy_Person',
    'APE_Person',
    'Archnet_Org',
    'BAnQ_Person',
    'BDCYL_Person',
    'Sinica_Person',
    'Georgia_Bio_Person',
    'Georgia_Encyc_Person',
    'Georgia_Monument_Place',
    'DSI_Person',
    'CGIAR_Registry_Org',
    'Irish_Bio_Person',
    'Canadian_Bio_Person',
    'Welsh_Bio_Person',
    'Swedish_Bio_Person',
    'ADAGP_Person',
    'ABMC_Person',
    'NZ_Bio_Person',
    'US_Congress_Person',
    'Finland_Bio_Person',
    'Finland_Swedish_Bio_Person',
    'AFI_Person',
    'BPH_Journal',
    'Ulster_Bio_Person',
    'Swedish_Women_Bio_Person',
    'Poetry_America_Person',
    'CNKI_Institute_Org',
    'CTHS_Org',
    'Cistercian_Bio_Person',
    'DACS_Person',
    'DBA_Person',
    'APA_Psych_Concept',
    'ARABTERM_Concept',
    'Biology_Concept',
    'Icelandic_Concept',
    'Greek_Concept',
    'BookBrainz_Person',
    'BookBrainz_Org',
    'BookBrainz_Work',
    'BookBub_Person',
    'BookDepository_Org',
    'ISFDB_Person',
    'ISFDB_Org',
    'ISFDB_Work',
    'Bookogs_Work',
    'Catalan_Writers_Person',
    'Israeli_Creators_Person',
    'Poetry_Foundation_Person',
    'Poetry_Archive_Person',
    'Scottish_Poetry_Person',
    'Goodreads_Author_Id',
    'CLMP_Org',
    'IPG_Org',
    'Swedish_Lit_Bank_Person',
    'Hessian_Lit_Person',
    'Armenian_Lit_Person',
    'Kazakh_Lit_Person',
    'Alabama_Lit_Person',
    'Arab_Lit_Person',
    'Amazon_Author_Id',
    'Aozora_Lit_Person',
    'Hungarian_Namespace_Person',
    'Finnish_Gallery_Person',
    'Azerbaijan_Encyc_Person',
    'Georgia_Film_Person',
    'Danish_Film_Person',
    'Folklore_Thesaurus_Concept',
    'Swiss_Authors_Winner',
    'Freelance_Editorial_Winner',
    'Foreign_Missions_Person',
    'Software_Preservation_Org',
    'Sami_Publishers_Org',
    'Ukraine_History_Org',
    'Flanders_Arts_Person',
    'Ankara_Institute_Person',
    'Dharma_Drum_Person',
    'AIATSIS_Subject_Concept',
    'British_Museum_Concept',
    'BG_Academic_Person',
    'CAS_Chemical_Concept',
    'Romania_NGO_Org',
    'SFADB_Person',
    'UNITER_Person',
    'UNESCO_Concept',
    'African_Film_Person',
    'African_Music_Person',
    'BN_Brazil_Person',
    'BNP_Portugal_Org',
    'NLP_Poland_Org',
    'NL_Greece_Person',
    'GuideStar_Israel_Org',
    'Swedish_Academy_Person',
    'NAS_Member_Person',
    'NAE_Member_Person',
    'Medicine_France_Person',
    'Swedish_Letters_Person',
    'Saxon_Academy_Person',
    'Lombardia_Arch_Person',
    'Turin_University_Person',
    'Islamic_Arch_Work',
    'Oxford_Arch_Concept',
    'RS_Bio_Memoirs_Person',
    'British_Council_Person',
    'CWA_Writer_Person',
    'SciFi_Encyc_Person',
    'RS_Fellow_Person',
    'BDGest_Person',
    'Lambiek_Person',
    'Ricochet_Person',
    'Pixiv_Work',
    'Bologna_Fair_Org',
    'AniDB_Person',
    'DriveThruComics_Org',
    'LC_Childrens_Concept',
    'MSU_Comic_Art_Work',
    'Quadrinhopedia_Person',
    'VIAF_Personal']


TYPE_NAME_OVERRIDES = {
    "ACA_Person": "Person -- Canadian Cinema Academy",
    "RS_Past_Fellow_Person": "Person -- Royal Society (Past Fellows)",
    "Ads_Winner": "Winner -- Italian Theatre (Ads)",
    "FIPB_Org": "Organization -- Indian Publishers (FIPB)",
    "AUP_NZ_Org": "Organization -- New Zealand Univ Presses (AUP-NZ)",
    "Israel_Art_Person": "Person -- Israeli Art (Information Center)",
    "Israel_Antiquities_Place": "Location -- Israel Antiquities (IAA)",
    "Israel_Museum_Person": "Person -- Israel Museum Jerusalem",
    "Israel_Company_Org": "Organization -- Israeli Companies",
    "Mexico_Aviation_Org": "Organization -- Mexico Aviation (DGAC)",
    "Mexico_Museums_Place": "Location -- Mexico Museums (SIC)",
    "SA_English_Work": "Work -- South African English Dict",
    "EULAC_Org": "Organization -- Latam Univ Presses (EULAC)",
    "NLI_Israel_Org": "Organization -- National Library of Israel",
    "Egyptian_Museum_Org": "Organization -- Global Egyptian Museum",
    "MinCiencias_Colombia_Org": "Organization -- Colombia MinCiencias",
    "Nigeria_NL_Org": "Organization -- National Library of Nigeria",
    "Nigerian_Company_Org": "Organization -- Nigerian Companies",
    "SNIESS_Colombia_Org": "Organization -- Colombia Higher Ed (SNIESS)",
    "Vietnam_Company_Org": "Organization -- Vietnam Companies",
    "AGN_Colombia_Org": "Organization -- Colombia General Archive",
    "CanTho_Vietnam_Org": "Organization -- Vietnam Can Tho Science",
    "Egypt_GAFI_Org": "Organization -- Egypt GAFI Corporate",
    "BaFin_Org": "Organization -- German Financial (BaFin)",
    "Premiados_Person": "Person -- Spanish Award Winners",
    "Slovakia_History_Work": "Work -- History of Slovakia Bib",
    "Psychiatry_Bio_Person": "Person -- Biographical Archive Psychiatry",
    "Czech_Bio_Person": "Person -- Czech Biographical Dict",
    "Bulgarian_Antarctic_Place": "Location -- Bulgarian Antarctic",
    "PBN_Org": "Organization -- Polish Bibliography Network (PBN)",
    "AEUP_Org": "Organization -- European Univ Presses (AEUP)",
    "Algerian_NL_Person": "Person -- National Library of Algeria",
    "Bavarian_Monument_Auth_Place": "Location -- Bavarian Monument Authority",
    "BALaT_Person": "Person -- Belgian Art (BALaT)",
    "ArtHistorians_Person": "Person -- Art Historians Dictionary",
    "Indy_Place": "Location -- Encyclopedia of Indianapolis",
    "GRC_Org": "Organization -- Global Research Council (GRC)",
    "AICTE_Org": "Organization -- Indian Technical Ed (AICTE)",
    "AISHE_Org": "Organization -- Indian Higher Ed (AISHE)",
    "AJOL_Org_2": "Organization -- African Journal Registry",
    "ASCL_Work": "Work -- African Studies Abstracts",
    "Leiden_Place": "Location -- Leiden African Thesaurus",
    "ASI_Place": "Location -- Archaeological Survey India",
    "CiNii_Org": "Organization -- Japanese CiNii Institutions",
    "Garuda_Org_2": "Organization -- Indonesian Garuda Registry",
    "Indo_College_Org": "Organization -- Indonesian College Code",
    "BNB_Person": "Person -- National Library of Brazil",
    "Akadem_Person_2": "Person -- Russian Academy of Sciences (Direct)",
    "Brapci_Person": "Person -- Brapci (Brazil Science)",
    "CNKI_Person": "Person -- CNKI China Author",
    "OASPA_Org": "Organization -- Open Access Scholarly Pub (OASPA)",
    "ACUP_Org": "Organization -- Canadian Univ Presses (ACUP)",
    "UNE_Org": "Organization -- Spanish Univ Presses (UNE)",
    "AArU_Org": "Organization -- Arab Univ Association (AArU)",
    "UPI_Org": "Organization -- Italian Univ Presses (UPI)",
    "CEEOL_Org": "Organization -- Eastern European CEEOL",
    "CLACSO_Org": "Organization -- Latam Social Sciences (CLACSO)",
    "ASSAf_Org": "Organization -- South African Science (ASSAf)",
    "Garuda_Org": "Organization -- Indonesian Garuda Index",
    "MyJurnal_Org": "Organization -- Malaysian MyJurnal Index",
    "ABU_Org": "Organization -- Bolivian Univ Presses (ABU)",
    "AFPU_Org": "Organization -- French Univ Presses (AFPU)",
    "AG_Univerlage_Org": "Organization -- German Univ Presses (AG Univerlage)",
    "KUPA_Org": "Organization -- South Korean Univ Presses (KUPA)",
    "CUPA_Org": "Organization -- Chinese Univ Presses (CUPA)",
    "DOAB_Org": "Organization -- Open Access Books (DOAB)",
    "CharityCommission_Org": "Organization -- UK Charities",
    "ProjectMUSE_Org": "Organization -- ProjectMUSE Publishers",
    "JSTOR_Org": "Organization -- JSTOR Publishers",
    "Indonesia_Place": "Location -- BIG Indonesia",
    "DOAB_Org": "Organization -- Open Access Books (DOAB)",
    "CharityCommission_Org": "Organization -- UK Charities",
    "ProjectMUSE_Org": "Organization -- ProjectMUSE Publishers",
    "JSTOR_Org": "Organization -- JSTOR Publishers",
    "Indonesia_Place": "Location -- BIG Indonesia",
    "ANZL_Writer": "Person -- Academy of New Zealand Literature",
    "Academy_Awards_Nominee": "Winner -- Academy Awards Nominees",
    "Akadem_Person": "Person -- Russian Academy of Sciences",
    "Annuaire_Fondations_Org": "Organization -- Annuaire des Fondations",
    "LC_Work_Id": "Title -- id.loc.gov",
    "Google_Books": "Title -- Google Books",
    "OCLC_Record": "Title -- Worldcat",
    "HathiTrust": "Title -- HathiTrust",
    "VIAF_Title": "Title -- VIAF Work",
    "Wikidata_Title": "Title -- Wikidata Work",
    "OpenLibrary_Title": "Title -- Open Library Work",
    "CWGC_Person": "Person -- Commonwealth War Graves",
    "CGIAR_Org": "Organization -- CGIAR Research Centers",
    "IPA_Org": "Organization -- IPA Book Fairs",
    "PASA_Org": "Organization -- Publishers South Africa (PASA)",
    "UPAN_Org": "Organization -- Australasian Univ Presses (UPAN)",
    "AaRC_Winner": "Winner -- Brazil Academy of Arts",
    "RussianTV_Winner": "Winner -- Russian TV Academy",
    "IRINS_Org": "Organization -- Indian Research (IRINS)",
    "Barcelona_Heritage_Place": "Location -- Barcelona Heritage",
    "Gatehouse_Place": "Location -- Gatehouse Gazetteer",
    "ARTIC_Person": "Person -- Art Institute Chicago",
    "ARTIC_Work": "Work -- Art Institute Chicago",
    "ASEE_Person": "Person -- Engineering Education (ASEE)",
    "Drammen_Place": "Location -- Drammen Encyclopedia",
    "ELEM_Org": "Organization -- Mexican Literature (ELEM)",
    "Athens_Academy_Person": "Person -- Academy of Athens",
    "Rome_Academy_Person": "Person -- American Academy in Rome",
    "French_Academy_Science_Person": "Person -- French Academy of Sciences",
    "Korean_Academy_Science_Person": "Person -- Korean Academy of Science",
    "Liszt_Academy_Person": "Person -- Liszt Academy Lexikon",
    "APE_Person": "Person -- Archives Portal Europe",
    "Archnet_Org": "Organization -- Archnet Islamic Arch",
    "BAnQ_Person": "Person -- National Library Quebec",
    "BDCYL_Person": "Person -- Castilla y Leon Digital",
    "Sinica_Person": "Person -- Academia Sinica Taiwan",
    "Georgia_Bio_Person": "Person -- Georgia Biographical Dict",
    "Georgia_Encyc_Person": "Person -- New Georgia Encyclopedia",
    "Georgia_Monument_Place": "Location -- Georgia Monuments",
    "DSI_Person": "Person -- Scientific Illustrators (DSI)",
    "CGIAR_Registry_Org": "Organization -- CGIAR Registry",
    "Irish_Bio_Person": "Person -- Dictionary of Irish Bio",
    "Canadian_Bio_Person": "Person -- Dictionary of Canadian Bio",
    "Welsh_Bio_Person": "Person -- Dictionary of Welsh Bio",
    "Swedish_Bio_Person": "Person -- Swedish National Bio",
    "ADAGP_Person": "Person -- French Artists (ADAGP)",
    "ABMC_Person": "Person -- US Battle Monuments",
    "NZ_Bio_Person": "Person -- Dictionary of NZ Bio",
    "US_Congress_Person": "Person -- US Congress Biography",
    "Finland_Bio_Person": "Person -- BiographySampo Finland",
    "Finland_Swedish_Bio_Person": "Person -- Biografiskt Lexikon Finland",
    "AFI_Person": "Person -- American Film Institute",
    "BPH_Journal": "Journal -- Botanical Periodicals (BPH)",
    "Ulster_Bio_Person": "Person -- Dictionary of Ulster Bio",
    "Swedish_Women_Bio_Person": "Person -- Swedish Women Bio (SKBL)",
    "Poetry_America_Person": "Person -- Poetry Society of America",
    "CNKI_Institute_Org": "Organization -- CNKI China Institutes",
    "CTHS_Org": "Organization -- French Scholarly (CTHS)",
    "Cistercian_Bio_Person": "Person -- Cistercian Biography",
    "DACS_Person": "Person -- UK Artists (DACS)",
    "DBA_Person": "Person -- Danish Biographical Archive",
    "APA_Psych_Concept": "Concept -- APA Psychology",
    "ARABTERM_Concept": "Concept -- ARABTERM Technical",
    "Biology_Concept": "Concept -- Oxford Biology",
    "Icelandic_Concept": "Concept -- Contemporary Icelandic",
    "Greek_Concept": "Concept -- Ancient Greek Lexicon",
    "BookBrainz_Person": "Person -- BookBrainz Author",
    "BookBrainz_Org": "Organization -- BookBrainz Publisher",
    "BookBrainz_Work": "Work -- BookBrainz Work",
    "BookBub_Person": "Person -- BookBub Author",
    "BookDepository_Org": "Organization -- Book Depository",
    "ISFDB_Person": "Person -- ISFDB Spec Fic Author",
    "ISFDB_Org": "Organization -- ISFDB Spec Fic Publisher",
    "ISFDB_Work": "Work -- ISFDB Spec Fic Title",
    "Bookogs_Work": "Work -- Bookogs Inventory",
    "Catalan_Writers_Person": "Person -- Catalan Writers (AELC)",
    "Israeli_Creators_Person": "Person -- Israeli Creators (ACUM)",
    "Poetry_Foundation_Person": "Person -- Poetry Foundation",
    "Poetry_Archive_Person": "Person -- Poetry Archive",
    "Scottish_Poetry_Person": "Person -- Scottish Poetry Library",
    "Goodreads_Author_Id": "Person -- Goodreads Author",
    "CLMP_Org": "Organization -- US Indie Literary (CLMP)",
    "IPG_Org": "Organization -- UK Indie Publishers (IPG)",
    "Swedish_Lit_Bank_Person": "Person -- Swedish Literature Bank",
    "Hessian_Lit_Person": "Person -- Hessian Literature Council",
    "Armenian_Lit_Person": "Person -- Armenian Literature (Digilib)",
    "Kazakh_Lit_Person": "Person -- Kazakh Literature (Adebiportal)",
    "Alabama_Lit_Person": "Person -- Alabama Authors",
    "Arab_Lit_Person": "Person -- Arab Literature (Alsharekh)",
    "Amazon_Author_Id": "Person -- Amazon Creator ID",
    "Aozora_Lit_Person": "Person -- Aozora Bunko (Japan)",
    "Hungarian_Namespace_Person": "Person -- Hungarian National Namespace",
    "Finnish_Gallery_Person": "Person -- Finnish National Gallery",
    "Azerbaijan_Encyc_Person": "Person -- Azerbaijani National Encyc",
    "Georgia_Film_Person": "Person -- Georgian National Filmography",
    "Danish_Film_Person": "Person -- Danish National Filmography",
    "Folklore_Thesaurus_Concept": "Concept -- American Folklore Thesaurus",
    "Swiss_Authors_Winner": "Winner -- Swiss Authors (former)",
    "Freelance_Editorial_Winner": "Winner -- Freelance Editorial Assoc",
    "Foreign_Missions_Person": "Person -- Paris Foreign Missions",
    "Software_Preservation_Org": "Organization -- Software Preservation Society",
    "Sami_Publishers_Org": "Organization -- Sami Publishers Assoc",
    "Ukraine_History_Org": "Organization -- Ukraine History Inst",
    "Flanders_Arts_Person": "Person -- Flanders Arts Institute",
    "Ankara_Institute_Person": "Person -- British Inst Ankara",
    "Dharma_Drum_Person": "Person -- Dharma Drum Institute",
    "AIATSIS_Subject_Concept": "Concept -- AIATSIS Subject Thesaurus",
    "British_Museum_Concept": "Concept -- British Museum Thesaurus",
    "BG_Academic_Person": "Person -- Bulgaria Academic Staff",
    "CAS_Chemical_Concept": "Concept -- CAS Registry Number",
    "Romania_NGO_Org": "Organization -- Romanian NGO Registry",
    "SFADB_Person": "Person -- Sci-Fi Awards Database",
    "UNITER_Person": "Person -- Romanian Theatre (UNITER)",
    "UNESCO_Concept": "Concept -- UNESCO Thesaurus",
    "African_Film_Person": "Person -- African Film Database",
    "African_Music_Person": "Person -- African Music Library",
    "BN_Brazil_Person": "Person -- National Library of Brazil",
    "BNP_Portugal_Org": "Organization -- National Library Portugal",
    "NLP_Poland_Org": "Organization -- National Library Poland",
    "NL_Greece_Person": "Person -- National Library of Greece",
    "GuideStar_Israel_Org": "Organization -- Israeli GuideStar",
    "Swedish_Academy_Person": "Person -- Swedish Academy Member",
    "NAS_Member_Person": "Person -- National Academy Sciences",
    "NAE_Member_Person": "Person -- National Academy Engineering",
    "Medicine_France_Person": "Person -- French Academy Medicine",
    "Swedish_Letters_Person": "Person -- Royal Swedish Academy Letters",
    "Saxon_Academy_Person": "Person -- Saxon Academy of Sciences",
    "Lombardia_Arch_Person": "Person -- Lombardy Architecture",
    "Turin_University_Person": "Person -- University of Turin",
    "Islamic_Arch_Work": "Work -- Islamic Art & Architecture",
    "Oxford_Arch_Concept": "Concept -- Oxford Dict Architecture",
    "RS_Bio_Memoirs_Person": "Person -- Royal Society Memoirs",
    "British_Council_Person": "Person -- British Council Writers",
    "CWA_Writer_Person": "Person -- Crime Writers' Association",
    "SciFi_Encyc_Person": "Person -- Science Fiction Encyclopedia",
    "RS_Fellow_Person": "Person -- Royal Society Fellows",
    "BDGest_Person": "Person -- BD Gest Author",
    "Lambiek_Person": "Person -- Lambiek Comiclopedia",
    "Ricochet_Person": "Person -- Ricochet Youth Lit Author",
    "Pixiv_Work": "Work -- Pixiv Comic",
    "Bologna_Fair_Org": "Organization -- Bologna Book Fair Exhibitor",
    "AniDB_Person": "Person -- AniDB Anime Creators",
    "DriveThruComics_Org": "Organization -- DriveThruComics Publisher",
    "LC_Childrens_Concept": "Concept -- LC Children's Subject Headings",
    "MSU_Comic_Art_Work": "Work -- MSU Comic Art Collection",
    "Quadrinhopedia_Person": "Person -- Quadrinhopédia (Brazil)",
    "VIAF_Personal": "Name -- VIAF Personal",
}


TYPE_LABELS = {
    "Org": "Organization",
    "Person": "Person",
    "Personal": "Person",
    "Award": "Award",
    "Awards": "Award",
    "Prize": "Award",
    "Grant": "Award",
    "Winner": "Winner",
    "Fellow": "Person",
    "Place": "Location",
    "Location": "Location",
    "Work": "Work",
    "Journal": "Journal",
    "Publisher": "Publisher",
    "Entity": "Concept",
    "Item": "Work",
    "Author": "Person",
    "Writer": "Person",
}


def _type_name(type_id):
    if type_id in TYPE_NAME_OVERRIDES:
        return TYPE_NAME_OVERRIDES[type_id]

    parts = type_id.split("_")
    label = next((TYPE_LABELS[p] for p in reversed(parts) if p in TYPE_LABELS), "Entity")
    display = " ".join(parts).replace(" Id", " ID").replace(" 2", "")
    return f"{label} -- {display}"


manifest = {
    "versions": ["0.2"],
    "defaultTypes": [{"id": type_id, "name": _type_name(type_id)} for type_id in DEFAULT_TYPE_IDS],
    "identifierSpace": "/doc/#identifierSpace",
    "schemaSpace": "/doc/#schemaSpace",
    "name": "BookReconciler Service",
    "batchSize": 1,
    "preview": {
        "height": 200,
        "url": use_endpoint_address + "/api/v1/preview?id={{id}}",
        "width": 500,
    },
    "view": {
        "url": use_endpoint_address + "/api/v1/redirect?id={{id}}",
    },
    "suggest": {
        "property": {
            "service_url": use_endpoint_address + "/api/v1/reconcile",
            "service_path": "/suggest/property",
        },
    },
    "extend": {
        "propose_properties": {
            "service_url": use_endpoint_address + "/api/v1/reconcile",
            "service_path": "/extend_suggest",
        },
    },
}
