from os import environ

use_endpoint_address = "http://127.0.0.1:5001"
if environ.get("OR_IP") is not None:
    use_endpoint_address = environ.get("OR_IP")


DEFAULT_TYPE_IDS = ['ROR_Org',
    'OpenAlex_Org',
    'ISNI_Person',
    'GND_Person',
    'BnF_Person',
    'BNE_Person',
    'NDL_Person',
    'OpenCorporates_Org',
    'LCNAF_Person',
    'NTA_Person',
    'OpenLibrary_Author',
    'AAT_Award',
    'DataCite_Award',
    'GeoNames_Location',
    'TGN_Location',
    'Academy_Award',
    'NSF_Award',
    'PEN_Org',
    'Members_Org',
    'ACLS_Org',
    'IFLA_Org',
    'ISC_Org',
    'Alberta_Place',
    'OpenLibrary_Work',
    'SF_Awards_Person',
    'ACM_Awards_Person',
    'RSC_Fellow',
    'TWAS_Fellow',
    'EBU_Org',
    'EUNIC_Org',
    'ADB_Person',
    'ACM_Person',
    'BNMX_Person',
    'AIATSIS_Place',
    'Canada_Historic_Place',
    'ASCE_Landmark_Place',
    'ADB_Publication_Work',
    'AAGM_Artwork_Work',
    'Euro08_Winner',
    'TwoGIS_Place',
    'Academy_Awards_Film',
    'AwardsWinners_Artist',
    'ASCAP_Work',
    'HAL_Org',
    'AwardsWinners_Person',
    'ALS_Org',
    'AAA_Org',
    'JTI_Org',
    'AEDA_Place',
    'MedalHonor_Person',
    'AINM_Place',
    'ACER_Org',
    'ACUM_Org',
    'Euro08_Person',
    'HebrewTheatre_Person',
    'AMPAS_Item',
    'ANPI_Place',
    'SevenDays_Person',
    'AAA_UK_Org',
    'ADAL_Spain_Org',
    'Bavarian_Monument_Place',
    'Australian_Heritage_Place_2',
    'AILA_Org',
    'Altexto_Org',
    'Sloan_Prize',
    'AMPAS_Person_2',
    'AJOL_Org',
    'AJUP_Org',
    'AtomicHeritage_Org',
    'Antarctic_Place',
    'BaneNOR_Place',
    'ALCA_Person',
    'ALCUIN_Person',
    'AMNH_Org',
    'NYC_Art_Place',
    'ACNC_Org',
    'Georgia_Emigrants_Person',
    'CESAR_Person',
    'ARC_Grant',
    'OpenDOAR_Org',
    'RS_Memoirs_Person',
    'Rome_Fellow_Person',
    'Royal_Society_Person',
    'SAM_Gov_Org',
    'HAL_TEL_Work',
    'ACM_Author_Id',
    'JapanNTA_Org',
    'SherpaRomeo_Work',
    'IPEDS_Org',
    'Nobel_Person',
    'SECCIK_Org',
    'JTI_Org_2',
    'EU_Transparency_Org',
    'ERIHPLUS_Journal',
    'Crossref_Funder_Org',
    'ABEU_Org',
    'AfricanMinds_Org',
    'AlbinMichel_Person',
    'GrantNav_Prize',
    'AFNIL_Org',
    'ASEUC_Org',
    'AlternativaTeatral_Place',
    'BHF_Person',
    'REUN_Org',
    'AAGM_Org',
    'ReliefWeb_Org',
    'AmericanHeritage_Place',
    'ISIL_Org',
    'ODUCAL_Org',
    'AFAS_Person',
    'Ads_Work',
    'Antarctic_Place_2',
    'IFACCA_Org',
    'AGORHA_Person',
    'ACE_Org',
    'Bombardirov_Person',
    'ADB_Org_Auth',
    'AEF_Org',
    'ALPSP_Org',
    'ASALE_Org',
    're3data_Org',
    'RussianDict_Person',
    'ChineseBio_Person',
    'QueerScientists_Person',
    'AAMC_Org',
    'AALA_Org',
    'BabelNet_Entity',
    'CODEN_Work',
    'EuropePMC_Work',
    'OpenCitations_Work',
    'ThreeSixtyGiving_Org',
    'Grammy_Award',
    'Sirene_Org',
    'DOAJ_Journal',
    'IdRef_Person',
    'SBN_Work',
    'BVMC_Person',
    'GCD_Publisher',
    'SIC_Mexico',
    'GRID_Historical',
    'ProPublica_Org',
    'NLA_Person',
    'ANZL_Writer',
    'Academy_Awards_Nominee',
    'Akadem_Person',
    'Annuaire_Fondations_Org',
    'LC_Work_Id',
    'Google_Books',
    'OCLC_Record',
    'HathiTrust',
    'VIAF_Title',
    'Wikidata_Title',
    'OpenLibrary_Title',
    'ACA_Person',
    'RS_Past_Fellow_Person',
    'Ads_Winner',
    'FIPB_Org',
    'AUP_NZ_Org',
    'PBN_Org',
    'AEUP_Org',
    'Algerian_NL_Person',
    'Bavarian_Monument_Auth_Place',
    'BALaT_Person',
    'ArtHistorians_Person',
    'Indy_Place',
    'GRC_Org',
    'AICTE_Org',
    'AISHE_Org',
    'AJOL_Org_2',
    'ASCL_Work',
    'Leiden_Place',
    'ASI_Place',
    'CiNii_Org',
    'Garuda_Org_2',
    'Indo_College_Org',
    'BNB_Person',
    'Akadem_Person_2',
    'Brapci_Person',
    'CNKI_Person',
    'OASPA_Org',
    'ACUP_Org',
    'UNE_Org',
    'AArU_Org',
    'UPI_Org',
    'CEEOL_Org',
    'CLACSO_Org',
    'ASSAf_Org',
    'Garuda_Org',
    'MyJurnal_Org',
    'ABU_Org',
    'AFPU_Org',
    'AG_Univerlage_Org',
    'KUPA_Org',
    'CUPA_Org',
    'DOAB_Org',
    'CharityCommission_Org',
    'ProjectMUSE_Org',
    'JSTOR_Org',
    'Indonesia_Place',
    'CWGC_Person',
    'CGIAR_Org',
    'IPA_Org',
    'PASA_Org',
    'UPAN_Org',
    'AaRC_Winner',
    'RussianTV_Winner',
    'IRINS_Org',
    'Barcelona_Heritage_Place',
    'Gatehouse_Place',
    'ARTIC_Person',
    'ARTIC_Work',
    'ASEE_Person',
    'Drammen_Place',
    'ELEM_Org',
    'Athens_Academy_Person',
    'Rome_Academy_Person',
    'French_Academy_Science_Person',
    'Korean_Academy_Science_Person',
    'Liszt_Academy_Person',
    'APE_Person',
    'Archnet_Org',
    'BAnQ_Person',
    'BDCYL_Person',
    'Sinica_Person',
    'Georgia_Bio_Person',
    'Georgia_Encyc_Person',
    'Georgia_Monument_Place',
    'DSI_Person',
    'CGIAR_Registry_Org',
    'Irish_Bio_Person',
    'Canadian_Bio_Person',
    'Welsh_Bio_Person',
    'Swedish_Bio_Person',
    'ADAGP_Person',
    'ABMC_Person',
    'NZ_Bio_Person',
    'US_Congress_Person',
    'Finland_Bio_Person',
    'Finland_Swedish_Bio_Person',
    'VIAF_Personal']


TYPE_NAME_OVERRIDES = {
    "ACA_Person": "Person -- Canadian Cinema Academy",
    "RS_Past_Fellow_Person": "Person -- Royal Society (Past Fellows)",
    "Ads_Winner": "Winner -- Italian Theatre (Ads)",
    "FIPB_Org": "Organization -- Indian Publishers (FIPB)",
    "AUP_NZ_Org": "Organization -- New Zealand Univ Presses (AUP-NZ)",
    "PBN_Org": "Organization -- Polish Bibliography Network (PBN)",
    "AEUP_Org": "Organization -- European Univ Presses (AEUP)",
    "Algerian_NL_Person": "Person -- National Library of Algeria",
    "Bavarian_Monument_Auth_Place": "Location -- Bavarian Monument Authority",
    "BALaT_Person": "Person -- Belgian Art (BALaT)",
    "ArtHistorians_Person": "Person -- Art Historians Dictionary",
    "Indy_Place": "Location -- Encyclopedia of Indianapolis",
    "GRC_Org": "Organization -- Global Research Council (GRC)",
    "AICTE_Org": "Organization -- Indian Technical Ed (AICTE)",
    "AISHE_Org": "Organization -- Indian Higher Ed (AISHE)",
    "AJOL_Org_2": "Organization -- African Journal Registry",
    "ASCL_Work": "Work -- African Studies Abstracts",
    "Leiden_Place": "Location -- Leiden African Thesaurus",
    "ASI_Place": "Location -- Archaeological Survey India",
    "CiNii_Org": "Organization -- Japanese CiNii Institutions",
    "Garuda_Org_2": "Organization -- Indonesian Garuda Registry",
    "Indo_College_Org": "Organization -- Indonesian College Code",
    "BNB_Person": "Person -- National Library of Brazil",
    "Akadem_Person_2": "Person -- Russian Academy of Sciences (Direct)",
    "Brapci_Person": "Person -- Brapci (Brazil Science)",
    "CNKI_Person": "Person -- CNKI China Author",
    "OASPA_Org": "Organization -- Open Access Scholarly Pub (OASPA)",
    "ACUP_Org": "Organization -- Canadian Univ Presses (ACUP)",
    "UNE_Org": "Organization -- Spanish Univ Presses (UNE)",
    "AArU_Org": "Organization -- Arab Univ Association (AArU)",
    "UPI_Org": "Organization -- Italian Univ Presses (UPI)",
    "CEEOL_Org": "Organization -- Eastern European CEEOL",
    "CLACSO_Org": "Organization -- Latam Social Sciences (CLACSO)",
    "ASSAf_Org": "Organization -- South African Science (ASSAf)",
    "Garuda_Org": "Organization -- Indonesian Garuda Index",
    "MyJurnal_Org": "Organization -- Malaysian MyJurnal Index",
    "ABU_Org": "Organization -- Bolivian Univ Presses (ABU)",
    "AFPU_Org": "Organization -- French Univ Presses (AFPU)",
    "AG_Univerlage_Org": "Organization -- German Univ Presses (AG Univerlage)",
    "KUPA_Org": "Organization -- South Korean Univ Presses (KUPA)",
    "CUPA_Org": "Organization -- Chinese Univ Presses (CUPA)",
    "DOAB_Org": "Organization -- Open Access Books (DOAB)",
    "CharityCommission_Org": "Organization -- UK Charities",
    "ProjectMUSE_Org": "Organization -- ProjectMUSE Publishers",
    "JSTOR_Org": "Organization -- JSTOR Publishers",
    "Indonesia_Place": "Location -- BIG Indonesia",
    "DOAB_Org": "Organization -- Open Access Books (DOAB)",
    "CharityCommission_Org": "Organization -- UK Charities",
    "ProjectMUSE_Org": "Organization -- ProjectMUSE Publishers",
    "JSTOR_Org": "Organization -- JSTOR Publishers",
    "Indonesia_Place": "Location -- BIG Indonesia",
    "ANZL_Writer": "Person -- Academy of New Zealand Literature",
    "Academy_Awards_Nominee": "Winner -- Academy Awards Nominees",
    "Akadem_Person": "Person -- Russian Academy of Sciences",
    "Annuaire_Fondations_Org": "Organization -- Annuaire des Fondations",
    "LC_Work_Id": "Title -- id.loc.gov",
    "Google_Books": "Title -- Google Books",
    "OCLC_Record": "Title -- Worldcat",
    "HathiTrust": "Title -- HathiTrust",
    "VIAF_Title": "Title -- VIAF Work",
    "Wikidata_Title": "Title -- Wikidata Work",
    "OpenLibrary_Title": "Title -- Open Library Work",
    "CWGC_Person": "Person -- Commonwealth War Graves",
    "CGIAR_Org": "Organization -- CGIAR Research Centers",
    "IPA_Org": "Organization -- IPA Book Fairs",
    "PASA_Org": "Organization -- Publishers South Africa (PASA)",
    "UPAN_Org": "Organization -- Australasian Univ Presses (UPAN)",
    "AaRC_Winner": "Winner -- Brazil Academy of Arts",
    "RussianTV_Winner": "Winner -- Russian TV Academy",
    "IRINS_Org": "Organization -- Indian Research (IRINS)",
    "Barcelona_Heritage_Place": "Location -- Barcelona Heritage",
    "Gatehouse_Place": "Location -- Gatehouse Gazetteer",
    "ARTIC_Person": "Person -- Art Institute Chicago",
    "ARTIC_Work": "Work -- Art Institute Chicago",
    "ASEE_Person": "Person -- Engineering Education (ASEE)",
    "Drammen_Place": "Location -- Drammen Encyclopedia",
    "ELEM_Org": "Organization -- Mexican Literature (ELEM)",
    "Athens_Academy_Person": "Person -- Academy of Athens",
    "Rome_Academy_Person": "Person -- American Academy in Rome",
    "French_Academy_Science_Person": "Person -- French Academy of Sciences",
    "Korean_Academy_Science_Person": "Person -- Korean Academy of Science",
    "Liszt_Academy_Person": "Person -- Liszt Academy Lexikon",
    "APE_Person": "Person -- Archives Portal Europe",
    "Archnet_Org": "Organization -- Archnet Islamic Arch",
    "BAnQ_Person": "Person -- National Library Quebec",
    "BDCYL_Person": "Person -- Castilla y Leon Digital",
    "Sinica_Person": "Person -- Academia Sinica Taiwan",
    "Georgia_Bio_Person": "Person -- Georgia Biographical Dict",
    "Georgia_Encyc_Person": "Person -- New Georgia Encyclopedia",
    "Georgia_Monument_Place": "Location -- Georgia Monuments",
    "DSI_Person": "Person -- Scientific Illustrators (DSI)",
    "CGIAR_Registry_Org": "Organization -- CGIAR Registry",
    "Irish_Bio_Person": "Person -- Dictionary of Irish Bio",
    "Canadian_Bio_Person": "Person -- Dictionary of Canadian Bio",
    "Welsh_Bio_Person": "Person -- Dictionary of Welsh Bio",
    "Swedish_Bio_Person": "Person -- Swedish National Bio",
    "ADAGP_Person": "Person -- French Artists (ADAGP)",
    "ABMC_Person": "Person -- US Battle Monuments",
    "NZ_Bio_Person": "Person -- Dictionary of NZ Bio",
    "US_Congress_Person": "Person -- US Congress Biography",
    "Finland_Bio_Person": "Person -- BiographySampo Finland",
    "Finland_Swedish_Bio_Person": "Person -- Biografiskt Lexikon Finland",
    "VIAF_Personal": "Name -- VIAF Personal",
}


TYPE_LABELS = {
    "Org": "Organization",
    "Person": "Person",
    "Personal": "Person",
    "Award": "Award",
    "Awards": "Award",
    "Prize": "Award",
    "Grant": "Award",
    "Winner": "Winner",
    "Fellow": "Person",
    "Place": "Location",
    "Location": "Location",
    "Work": "Work",
    "Journal": "Journal",
    "Publisher": "Publisher",
    "Entity": "Concept",
    "Item": "Work",
    "Author": "Person",
    "Writer": "Person",
}


def _type_name(type_id):
    if type_id in TYPE_NAME_OVERRIDES:
        return TYPE_NAME_OVERRIDES[type_id]

    parts = type_id.split("_")
    label = next((TYPE_LABELS[p] for p in reversed(parts) if p in TYPE_LABELS), "Entity")
    display = " ".join(parts).replace(" Id", " ID").replace(" 2", "")
    return f"{label} -- {display}"


manifest = {
    "versions": ["0.2"],
    "defaultTypes": [{"id": type_id, "name": _type_name(type_id)} for type_id in DEFAULT_TYPE_IDS],
    "identifierSpace": "/doc/#identifierSpace",
    "schemaSpace": "/doc/#schemaSpace",
    "name": "BookReconciler Service",
    "batchSize": 1,
    "preview": {
        "height": 200,
        "url": use_endpoint_address + "/api/v1/preview?id={{id}}",
        "width": 500,
    },
    "view": {
        "url": use_endpoint_address + "/api/v1/redirect?id={{id}}",
    },
    "suggest": {
        "property": {
            "service_url": use_endpoint_address + "/api/v1/reconcile",
            "service_path": "/suggest/property",
        },
    },
    "extend": {
        "propose_properties": {
            "service_url": use_endpoint_address + "/api/v1/reconcile",
            "service_path": "/extend_suggest",
        },
    },
}
